#!/usr/bin/env node
// Writes src/data/latest.json (the newest release: version, date, size,
// SHA256) and public/_redirects (/download/mac -> that .dmg), so the site
// never hard-codes a version. The site offers only the newest build.
//
//   node scripts/sync-latest.mjs
//
// Env:
//   RELEASES_REPO   owner/name to read the latest release from (default cc-vb/dictator)
//   GITHUB_TOKEN    needed once the repo is private
//   DOWNLOAD_BASE   where Dictator.dmg is served from. Unset, the link points at
//                   the GitHub release asset. Set (e.g. https://pub-x.r2.dev),
//                   it becomes DOWNLOAD_BASE/Dictator.dmg.
//
// If the API cannot be reached the existing latest.json is kept, so an
// offline build still works with the last known release.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const REPO = process.env.RELEASES_REPO || "cc-vb/dictator";
const TOKEN = process.env.GITHUB_TOKEN || "";
const BASE = (process.env.DOWNLOAD_BASE || "").replace(/\/$/, "");

const DATA = fileURLToPath(new URL("../src/data/latest.json", import.meta.url));
const REDIRECTS = fileURLToPath(new URL("../public/_redirects", import.meta.url));

async function fetchLatest() {
  const headers = { Accept: "application/vnd.github+json", "User-Agent": "dictator-website" };
  if (TOKEN) headers.Authorization = `Bearer ${TOKEN}`;
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, { headers });
  if (!res.ok) throw new Error(`GitHub API ${res.status} ${res.statusText}`);
  const rel = await res.json();

  const version = rel.tag_name.replace(/^v/, "");
  // Dictator.dmg is the same file as Dictator-<version>.dmg under the name the
  // install guide uses, so what people download matches what the page says.
  const asset = rel.assets.find((a) => a.name === "Dictator.dmg");
  if (!asset) throw new Error(`release ${rel.tag_name} has no Dictator.dmg`);

  return {
    version,
    date: rel.published_at,
    mac: {
      url: BASE ? `${BASE}/Dictator.dmg` : asset.browser_download_url,
      size: asset.size,
      sha256: (asset.digest || "").replace(/^sha256:/, ""),
      minOS: "14.0",
      arch: "Apple silicon",
    },
  };
}

async function main() {
  let latest;
  try {
    latest = await fetchLatest();
  } catch (err) {
    latest = JSON.parse(await readFile(DATA, "utf8").catch(() => "null"));
    if (!latest?.version) throw err;
    console.warn(`sync-latest: ${err.message}; keeping ${latest.version}`);
  }

  await writeFile(DATA, JSON.stringify(latest, null, 2) + "\n");
  await writeFile(
    REDIRECTS,
    `# Generated by scripts/sync-latest.mjs. Do not edit by hand.\n/download/mac  ${latest.mac.url}  302\n`,
  );
  console.log(`sync-latest: ${latest.version}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
