#!/usr/bin/env node
// Writes src/data/latest.json (the newest release: version, date, size,
// SHA256) and public/_redirects, so the site never hard-codes a version. The
// site offers only the newest build.
//
//   node scripts/sync-latest.mjs
//
// Where the release comes from:
//   DOWNLOAD_BASE set   the R2 bucket's latest.json (tools/publish_r2.sh writes
//                       it). The redirects send /download/mac to its
//                       Dictator.dmg and /appcast.xml to its feed, the address
//                       installed apps check for updates.
//   unset               the latest GitHub release, as before the move.
//
// DOWNLOAD_BASE defaults to the value in ../tools/hosting.env, the same file
// the release scripts read, so the address is set in one place.
//
// Env: DOWNLOAD_BASE, RELEASES_REPO (default cc-vb/dictator), GITHUB_TOKEN.
//
// If the API cannot be reached the existing latest.json is kept, so an
// offline build still works with the last known release.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const HOSTING = fileURLToPath(new URL("../../tools/hosting.env", import.meta.url));

async function hostingValue(name) {
  const text = await readFile(HOSTING, "utf8").catch(() => "");
  const line = text.split("\n").find((l) => l.startsWith(`${name}=`));
  return line ? line.slice(name.length + 1).trim() : "";
}

const REPO = process.env.RELEASES_REPO || "cc-vb/dictator";
const TOKEN = process.env.GITHUB_TOKEN || "";
const BASE = (process.env.DOWNLOAD_BASE ?? (await hostingValue("DOWNLOAD_BASE"))).replace(/\/$/, "");

const DATA = fileURLToPath(new URL("../src/data/latest.json", import.meta.url));
const REDIRECTS = fileURLToPath(new URL("../public/_redirects", import.meta.url));

async function fetchFromBucket() {
  const res = await fetch(`${BASE}/latest.json`, { cache: "no-store" });
  if (!res.ok) throw new Error(`${BASE}/latest.json ${res.status} ${res.statusText}`);
  return res.json();
}

async function fetchFromGitHub() {
  const headers = { Accept: "application/vnd.github+json", "User-Agent": "dictator-website" };
  if (TOKEN) headers.Authorization = `Bearer ${TOKEN}`;
  const res = await fetch(`https://api.github.com/repos/${REPO}/releases/latest`, { headers });
  if (!res.ok) throw new Error(`GitHub API ${res.status} ${res.statusText}`);
  const rel = await res.json();

  const version = rel.tag_name.replace(/^v/, "");
  // Dictator.dmg is the same file as Dictator-<version>.dmg under the name the
  // install guide uses, so what people download matches what the page says.
  const asset = rel.assets.find((a) => a.name === "Dictator.dmg");
  if (!asset) throw new Error(`release ${rel.tag_name} has no Dictator.dmg`);

  return {
    version,
    date: rel.published_at,
    mac: {
      url: asset.browser_download_url,
      size: asset.size,
      sha256: (asset.digest || "").replace(/^sha256:/, ""),
      minOS: "14.0",
      arch: "Apple silicon",
    },
  };
}

async function main() {
  let latest;
  try {
    latest = BASE ? await fetchFromBucket() : await fetchFromGitHub();
  } catch (err) {
    latest = JSON.parse(await readFile(DATA, "utf8").catch(() => "null"));
    if (!latest?.version) throw err;
    console.warn(`sync-latest: ${err.message}; keeping ${latest.version}`);
  }

  await writeFile(DATA, JSON.stringify(latest, null, 2) + "\n");
  const redirects = [
    "# Generated by scripts/sync-latest.mjs. Do not edit by hand.",
    `/download/mac  ${latest.mac.url}  302`,
  ];
  if (BASE) redirects.push(`/appcast.xml  ${BASE}/appcast.xml  302`);
  await writeFile(REDIRECTS, redirects.join("\n") + "\n");
  console.log(`sync-latest: ${latest.version}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
