#!/usr/bin/env node
// Writes src/data/latest.json (the newest release: version, date, size,
// SHA256) and public/_redirects, so the site never hard-codes a version or an
// address. Both files are generated on every build and are not committed.
//
//   node scripts/sync-latest.mjs
//
// The release comes from DICTATOR_DOWNLOAD_BASE (the environment or the root
// .env): the R2 bucket's latest.json, which tools/publish_r2.sh writes.
// /download/mac goes to its versioned .dmg and /appcast.xml to its feed, the
// address installed apps check for updates.
//
// If the bucket cannot be reached, a latest.json left by an earlier run is
// kept, so an offline rebuild still works. A first build needs a release in
// the bucket.

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { envUrl, loadRootEnv } from "./env.mjs";

loadRootEnv();

const BASE = envUrl("DICTATOR_DOWNLOAD_BASE");

const DATA = fileURLToPath(new URL("../src/data/latest.json", import.meta.url));
const REDIRECTS = fileURLToPath(new URL("../public/_redirects", import.meta.url));

async function fetchFromBucket() {
  const res = await fetch(`${BASE}/latest.json`, { cache: "no-store" });
  if (!res.ok) throw new Error(`${BASE}/latest.json ${res.status} ${res.statusText}`);
  return res.json();
}

async function main() {
  if (!BASE) {
    throw new Error("sync-latest: set DICTATOR_DOWNLOAD_BASE (environment or .env)");
  }

  let latest;
  try {
    latest = await fetchFromBucket();
  } catch (err) {
    latest = JSON.parse(await readFile(DATA, "utf8").catch(() => "null"));
    if (!latest?.version) throw err;
    console.warn(`sync-latest: ${err.message}; keeping ${latest.version}`);
  }

  await writeFile(DATA, JSON.stringify(latest, null, 2) + "\n");
  const redirects = [
    "# Generated by scripts/sync-latest.mjs. Do not edit by hand.",
    `/download/mac  ${latest.mac.url}  302`,
    `/appcast.xml  ${BASE}/appcast.xml  302`,
  ];
  await writeFile(REDIRECTS, redirects.join("\n") + "\n");
  console.log(`sync-latest: ${latest.version} from ${BASE}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
